# Generated by Django 6.0.7 on 2026-07-22 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por compra'), ('SALIDA_VENTA', 'Salida por venta'), ('AJUSTE_ENTRADA', 'Ajuste de entrada'), ('AJUSTE_SALIDA', 'Ajuste de salida')], db_index=True, max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.PositiveIntegerField(verbose_name='Stock posterior')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del movimiento')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='compras.compra', verbose_name='Compra relacionada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha_movimiento', '-id'],
            },
        ),
    ]
