# Generated by Django 6.0.7 on 2026-08-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo_venta',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Código interno de venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='documento_cliente_ocasional',
            field=models.CharField(blank=True, max_length=30, verbose_name='Documento del cliente ocasional'),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente_ocasional',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del cliente ocasional'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente_ocasional',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del cliente ocasional'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_cliente',
            field=models.CharField(choices=[('REGISTRADO', 'Cliente registrado'), ('OCASIONAL', 'Cliente ocasional')], db_index=True, default='REGISTRADO', max_length=20, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='Cliente registrado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_comprobante',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Número de factura o comprobante externo'),
        ),
    ]
