# Generated by Django 6.0.7 on 2026-08-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_codigo_venta_venta_documento_cliente_ocasional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.PositiveIntegerField(unique=True, verbose_name='Gestión')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último número utilizado')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Secuencia de venta',
                'verbose_name_plural': 'Secuencias de venta',
                'ordering': ['-gestion'],
            },
        ),
    ]
