# Generated by Django 6.0.7 on 2026-08-04 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_secuenciaventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
