# Generated by Django 6.0.7 on 2026-08-06 01:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_fecha_anulacion_venta_fecha_confirmacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento_credito',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento del crédito'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_inicial',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Pago mediante QR'), ('DEPOSITO', 'Depósito bancario')], max_length=20, verbose_name='Método del pago inicial'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto del pago inicial'),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago_inicial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia del pago inicial'),
        ),
    ]
