# Generated by Django 6.0.7 on 2026-07-22 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(db_index=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(db_index=True, max_length=100, verbose_name='Modelo')),
                ('anio_desde', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año desde')),
                ('anio_hasta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año hasta')),
                ('motor', models.CharField(blank=True, max_length=100, verbose_name='Motor')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo', 'anio_desde'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='productos.producto', verbose_name='Producto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_compatibles', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Compatibilidad de producto',
                'verbose_name_plural': 'Compatibilidades de productos',
                'ordering': ['vehiculo__marca', 'vehiculo__modelo'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'vehiculo'), name='compatibilidad_producto_vehiculo_unica')],
            },
        ),
    ]
