# Generated by Django 6.0.7 on 2026-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio_compra_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedores_habituales',
            field=models.ManyToManyField(blank=True, related_name='productos_habituales', to='proveedores.proveedor', verbose_name='Proveedores habituales'),
        ),
    ]
