# Generated by Django 6.0.7 on 2026-07-25 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('umbral_fast', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Umbral Fast')),
                ('umbral_slow', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Umbral Slow')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_clasificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parámetro de clasificación',
                'verbose_name_plural': 'Parámetros de clasificación',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.PositiveIntegerField()),
                ('probabilidad', models.DecimalField(decimal_places=6, max_digits=8)),
                ('categoria', models.CharField(choices=[('FAST', 'Fast Moving'), ('SLOW', 'Slow Moving'), ('NON', 'Non Moving')], max_length=10)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='clasificacion.parametroclasificacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Resultado de clasificación',
                'verbose_name_plural': 'Resultados de clasificación',
                'ordering': ['categoria', '-probabilidad', 'producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('parametro', 'producto'), name='clasificacion_unica_producto_parametro')],
            },
        ),
    ]
