# Generated by Django 6.0.7 on 2026-08-03 18:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de venta'),
            preserve_default=False,
        ),
    ]
