# Generated by Django 6.0.7 on 2026-08-04 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_fecha_anulacion_compra_motivo_anulacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario_confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
