# Generated by Django 6.0.7 on 2026-08-04 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_fecha_confirmacion_and_more'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_comprobante', ''), _negated=True), fields=('proveedor', 'tipo_comprobante', 'numero_comprobante'), name='compra_comprobante_unico_proveedor_tipo'),
        ),
    ]
