# Generated by Django 6.0.7 on 2026-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compra_compra_comprobante_unico_proveedor_tipo'),
        ('productos', '0004_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', models.F('costo_unitario'))), name='detalle_compra_precio_venta_mayor_igual_costo'),
        ),
    ]
