# Generated by Django 6.0.7 on 2026-08-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_detallecompra_detalle_compra_precio_venta_mayor_igual_costo'),
        ('productos', '0004_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detalle_compra_cantidad_minima_uno'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gt', 0)), name='detalle_compra_costo_unitario_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gt', 0)), name='detalle_compra_precio_venta_positivo'),
        ),
    ]
