# Generated by Django 6.0.7 on 2026-07-23 05:29

import creditos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio')),
                ('fecha_vencimiento', models.DateField(db_index=True, default=creditos.models.fecha_vencimiento_predeterminada, verbose_name='Fecha de vencimiento')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto total')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo pendiente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credito', to='ventas.venta', verbose_name='Venta relacionada')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto pagado')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Pago mediante QR'), ('DEPOSITO', 'Depósito bancario')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia del pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.credito', verbose_name='Crédito')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_credito_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de crédito',
                'verbose_name_plural': 'Pagos de créditos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
