# Generated by Django 6.0.7 on 2026-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(db_index=True, max_length=150, verbose_name='Nombre o razón social')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='NIT')),
                ('persona_contacto', models.CharField(blank=True, max_length=120, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
